/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.Archivo;
import Clases.Automata;
import Clases.Lexema;
import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.text.BadLocationException;
import javax.swing.text.Caret;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Highlighter;

/**
 *
 * @author emili
 */
public class Form1 extends javax.swing.JFrame {

    /*Instancio objeto para manejo de archivos*/
    Archivo archivo = new Archivo();
    /*Lista para los tokens generados para automatas*/
    private ArrayList tokens = new ArrayList();
    ImageIcon Boton1 = new ImageIcon("carpeta.png");
    ImageIcon Boton2 = new ImageIcon("jugar.png");
    ImageIcon Boton3 = new ImageIcon("Borrar.png");
    ImageIcon Boton4 = new ImageIcon("salvar.png");
    ImageIcon Boton5 = new ImageIcon("Exportar.png");
    ImageIcon Fondo1 = new ImageIcon("Fondo1.jpg");
    ImageIcon Icono = new ImageIcon("Error.png");
    ImageIcon lupa = new ImageIcon("Lupa.png");

    /**
     * Creates new form Form1
     */
    public Form1() {
        initComponents();

        Trasparencia();
        Cargar.setIcon(new ImageIcon(Boton1.getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH)));
        Ejecutar.setIcon(new ImageIcon(Boton2.getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH)));
        Limpiar.setIcon(new ImageIcon(Boton3.getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH)));
        Guardar.setIcon(new ImageIcon(Boton4.getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH)));
        IconoError.setIcon(new ImageIcon(Icono.getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH)));
        Exportar.setIcon(new ImageIcon(Boton5.getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH)));
        Fondo.setIcon(new ImageIcon(Fondo1.getImage().getScaledInstance(1200, 690, Image.SCALE_SMOOTH)));
        Buscar.setIcon(new ImageIcon(lupa.getImage().getScaledInstance(25, 32, Image.SCALE_SMOOTH)));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLinea = new javax.swing.JLabel();
        lblColumna = new javax.swing.JLabel();
        Cargar = new javax.swing.JButton();
        Ejecutar = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();
        Guardar = new javax.swing.JButton();
        Exportar = new javax.swing.JButton();
        estado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Buscar = new javax.swing.JButton();
        txtbuscar = new javax.swing.JTextField();
        IconoError = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaTexto = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaErrores = new javax.swing.JTextArea();
        Fondo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        AreaTexto = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLinea.setBackground(new java.awt.Color(255, 255, 255));
        lblLinea.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblLinea.setForeground(new java.awt.Color(255, 255, 255));
        lblLinea.setText("Linea");
        jPanel1.add(lblLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, -1, -1));

        lblColumna.setBackground(new java.awt.Color(255, 255, 255));
        lblColumna.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblColumna.setForeground(new java.awt.Color(255, 255, 255));
        lblColumna.setText("Columna");
        jPanel1.add(lblColumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, -1, -1));

        Cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarActionPerformed(evt);
            }
        });
        jPanel1.add(Cargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 80, 40));

        Ejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EjecutarActionPerformed(evt);
            }
        });
        jPanel1.add(Ejecutar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 80, 40));

        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 80, 40));

        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        jPanel1.add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 80, 40));

        Exportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportarActionPerformed(evt);
            }
        });
        jPanel1.add(Exportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 270, 80, 40));

        estado.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 190, 40));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Exportar Reportes");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 310, 120, 60));

        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        jPanel1.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 30, 30));
        jPanel1.add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 30));
        jPanel1.add(IconoError, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 50, 50));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Errores Lexicos:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 550, 110, 20));

        areaTexto.setColumns(20);
        areaTexto.setRows(5);
        jScrollPane1.setViewportView(areaTexto);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 710, 290));

        areaErrores.setColumns(20);
        areaErrores.setRows(5);
        jScrollPane3.setViewportView(areaErrores);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 710, 300));
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 690));

        AreaTexto.setColumns(20);
        AreaTexto.setRows(5);
        jScrollPane2.setViewportView(AreaTexto);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 570, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarActionPerformed
        // TODO add your handling code here:
        if (archivo.getSeleccionar().showDialog(null, "Abrir") == JFileChooser.APPROVE_OPTION) {
            archivo.setArchivo(archivo.getSeleccionar().getSelectedFile());
            if (archivo.getArchivo().canRead()) {
                if (archivo.getArchivo().getName().endsWith("txt")) {
                    String Documento = archivo.abrirArchivo(archivo.getArchivo());
                    areaTexto.setText(Documento);
                } else {
                    JOptionPane.showMessageDialog(null, "Archivo no compatible" + JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_CargarActionPerformed

    private void EjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EjecutarActionPerformed
        // TODO add your handling code here:
        //Instancio objeto de la clase automata
        Automata analizador = new Automata();
        //Se envia el texto a analizar
        analizador.analizadorAutomata(areaTexto.getText());
        //Clono el arraylist generado
        tokens = (ArrayList) analizador.getListaLexema().clone();
        //Metodo para mostrar tokes
        mostrarTokens();
        analizador.mostrarTokens();

        //Verifica si existen errores
        if (verificarErrores()) {
            JOptionPane.showMessageDialog(null, "Compilacion Correcta");
        } else {
            JOptionPane.showMessageDialog(null, "Hay Errores Lexicos");
        }
    }//GEN-LAST:event_EjecutarActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:

        Exportar();
    }//GEN-LAST:event_GuardarActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        // TODO add your handling code here:
        areaTexto.setText(null);
        areaErrores.setText(null);
    }//GEN-LAST:event_LimpiarActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
        buscarTexto();
    }//GEN-LAST:event_BuscarActionPerformed

    private void ExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportarActionPerformed
        // TODO add your handling code here:\
        Reportes();
    }//GEN-LAST:event_ExportarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form1().setVisible(true);
            }
        });
    }

    public void Trasparencia() {
        Cargar.setOpaque(false);
        Cargar.setContentAreaFilled(false);
        Ejecutar.setOpaque(false);
        Ejecutar.setContentAreaFilled(false);
        Limpiar.setOpaque(false);
        Limpiar.setContentAreaFilled(false);
        Guardar.setOpaque(false);
        Guardar.setContentAreaFilled(false);
        Buscar.setOpaque(false);
        Buscar.setContentAreaFilled(false);
        Exportar.setOpaque(false);
        Exportar.setContentAreaFilled(false);
    }

    /*Regresa si encuentra errores*/
    public Boolean verificarErrores() {
        if (areaErrores.getText().equals("")) {
            return true;
        } else {
            return false;
        }
    }

    /*Obtiene la fila y columna actual*/
    public void getColumnaFila() throws BadLocationException {
        int index = 0;
        int line = 0;
        areaTexto.setSelectionStart(0);
        areaTexto.getLineOfOffset(index);

        int firstChar = areaTexto.getLineStartOffset(line);
        int column = index - firstChar;
        lblLinea.setText("Linea: " + (line + 1));
        lblColumna.setText("Columna: " + column);
    }

    /* Muestra y pinta los tokens */
    public void mostrarTokens() {
        //Contador de errores
        int contErrores = 1;
        //Se limpia dos areas de texto
        areaErrores.setText(null);

        //Analiza el arraylist y clasifica los tokens
        for (int i = 0; i < tokens.size(); i++) {
            Lexema lexema = (Lexema) tokens.get(i);
            //Si es entero lo pinta de morado
            if (lexema.getTipo().equals("Entero")) {

                AreaTexto.append(lexema.getLexema() + " " + lexema.getTipo());

            } //Si es decimal 
            else if (lexema.getTipo().equals("Decimal")) {

                AreaTexto.append(lexema.getLexema() + " " + lexema.getTipo());
            } //Si es cadena 
            else if (lexema.getTipo().equals("Cadena")) {

                AreaTexto.append(lexema.getLexema() + " " + lexema.getTipo());
            } //Si es booleano 
            else if (lexema.getTipo().equals("Booleano")) {

                AreaTexto.append(lexema.getLexema() + " " + lexema.getTipo());
            } //Si es caracter 
            else if (lexema.getTipo().equals("Caracter")) {

                AreaTexto.append(lexema.getLexema() + " " + lexema.getTipo());
            } //Si es un operador 
            else if (lexema.getTipo().equals("Operador")) {

                AreaTexto.append(lexema.getLexema() + " " + lexema.getTipo());
            } //Si es una asignacion 
            else if (lexema.getTipo().equals("Asignacion")) {

                AreaTexto.append(lexema.getLexema() + " " + lexema.getTipo());
            } //Si es un comentario 
            else if (lexema.getTipo().equals("Comentario")) {

                AreaTexto.append(lexema.getLexema() + " " + lexema.getTipo());
            } else if (lexema.getTipo().equals("Error")) {

                AreaTexto.append(lexema.getLexema());
                areaErrores.append(contErrores + ") " + lexema.getLexema() + " " + lexema.getTipo());
                contErrores++;
                areaErrores.append("\n");
            } else if (!lexema.getTipo().equals("Enter")) {

                AreaTexto.append(lexema.getLexema());
            }

            //Inserta enters o espacios
            if (lexema.getTipo().equals("Enter")) {
                AreaTexto.append("\n");
            } else {
                AreaTexto.append(" ");
            }

        }
    }

    public void Exportar() {
        try {
            JFileChooser archivo = new JFileChooser(System.getProperty("user.dir"));
            archivo.showSaveDialog(this);
            if (archivo.getSelectedFile() != null) {
                try (FileWriter guardado = new FileWriter(archivo.getSelectedFile())) {
                    guardado.write(areaTexto.getText());
                    JOptionPane.showMessageDialog(rootPane, "El archivo fue guardado con éxito en la ruta establecida");
                }
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
    
    public void Reportes() {
        try {
            JFileChooser archivo = new JFileChooser(System.getProperty("user.dir"));
            archivo.showSaveDialog(this);
            if (archivo.getSelectedFile() != null) {
                try (FileWriter guardado = new FileWriter(archivo.getSelectedFile())) {
                    guardado.write(AreaTexto.getText());
                    JOptionPane.showMessageDialog(rootPane, "El archivo fue guardado con éxito en la ruta establecida");
                }
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        
            try {
            JFileChooser archivo = new JFileChooser(System.getProperty("user.dir"));
            archivo.showSaveDialog(this);
            if (archivo.getSelectedFile() != null) {
                try (FileWriter guardado = new FileWriter(archivo.getSelectedFile())) {
                    guardado.write(areaErrores.getText());
                    JOptionPane.showMessageDialog(rootPane, "El archivo de ERRORES fue guardado con éxito en la ruta establecida");
                }
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    public void buscarTexto() {

        String s = txtbuscar.getText();

        if (s.length() > 0) {
            String contenido = areaTexto.getText();
            int index = contenido.indexOf(s, 0);
            if (index >= 0) {
                int end = index + s.length();
                areaTexto.setCaretPosition(end);
                estado.setText("'" + s + "' fue encontrado.");
            } else {
                txtbuscar.setBackground(Color.ORANGE);
                estado.setText("'" + s + "' no se ha encontrado.");
            }
        } else {
            estado.setText("Digite la palabra a buscar.");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaTexto;
    private javax.swing.JButton Buscar;
    private javax.swing.JButton Cargar;
    private javax.swing.JButton Ejecutar;
    private javax.swing.JButton Exportar;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton Guardar;
    private javax.swing.JLabel IconoError;
    private javax.swing.JButton Limpiar;
    private javax.swing.JTextArea areaErrores;
    private javax.swing.JTextArea areaTexto;
    private javax.swing.JLabel estado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblColumna;
    private javax.swing.JLabel lblLinea;
    private javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables
}
